matrix:
- name: Markdown
  aspell:
    lang: es
    ignore-case: true
    mode: markdown
  dictionary:
    wordlists:
    - .github/config/.wordlist.txt
    encoding: utf-8
  sources:
  - '_posts/*.md'
  default_encoding: utf-8