matrix:
- name: Markdown
  aspell:
    lang: es, en
    ignore-case: true
    mode: markdown
  dictionary:
    wordlists:
    - .github/config/.wordlist.txt
    encoding: utf-8
  sources:
  - '_posts/2023-*.md'
  - '_posts/2022-*.md'
  default_encoding: utf-8
