name: Check style
on: push
jobs:
  check-style:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@main
    - name: Line ends with a period
      run: |
        cat _posts/2023-1*.md > _posts/all.md
        echo $(egrep "^\.$" _posts/all.md | egrep "^\w" | egrep -v ":$" | egrep -v "^1\. " | egrep -v "^author: " | egrep -v "^layout: " | egrep -v "^tags: " | egrep -v "^title: ") > lines_without_period.tmp
        cat lines_without_period.tmp
        [[ $(cat lines_without_period.tmp | wc -w) -eq 0 ]]
    - name: Sentences are short
      run: |
        cat _posts/2023-1*.md > _posts/all.md
        IFS=$'\n' && for line in $(egrep "\.$" _posts/all.md);   do echo "$line" ; [[ $(echo "$line" | wc -w) -le 25 ]] ; done
        IFS=$'\n' && for line in $(egrep "^\W" _posts/all.md);   do echo "$line" ; [[ $(echo "$line" | wc -w) -le 25 ]] ; done
        IFS=$'\n' && for line in $(egrep ":$" _posts/all.md);    do echo "$line" ; [[ $(echo "$line" | wc -w) -le 25 ]] ; done
        IFS=$'\n' && for line in $(egrep "^1\. " _posts/all.md); do echo "$line" ; [[ $(echo "$line" | wc -w) -le 25 ]] ; done
