name: Check style
on: push
jobs:

  check:
    name: Check style and spelling
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@main
    - name: Build Docker image
      run: docker build --tag islasgeci/islasgeci.github.io .
    - name: Run checks
      run: docker run --volume $PWD:/workdir islasgeci/islasgeci.github.io make check
